language: python
sudo: required
python:
- '2.7'
install:
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install tox>=2.3.1 coveralls
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . )
after_success: coveralls --verbose
branches:
  only:
  - master
  - /^v.*$/
deploy:
  provider: pypi
  user: tcarel
  password:
    secure: Gi0fEiXWWAmdl9PLKAjinvKVFb1KYKqj1FVxIA/ZOIV4uNpz38HHyLvGI+DSvqoEKmqfPg4uT6DGYv8LeexbP0SMLrT73Qh4wPjaxGTTlnLgypzStnchzzTF+/eZJSxsZPsWO5WD0iakSiyO11jxhdK7RbqLfYS/+XCl78a6/wh7cK2PZ6tIgi985SaClbLsQtzd9EdEsPyoo6V3L8VDutY7F5SzVg13V05kMC7KApM1Iulh+iwVePn/iMHAErrl2i4voFWE+RePgTIFYoIViq8Rew1V14Qe78hiT1AKsoi37F1d5ThLiIB3LWvGN6ZF2qaL9XpQ9aPuOFpuJ6PsL0mOPE+6KjbvWwN25daGIbidoUyEHDrjtZhbD8c1pQWPWkJ01TzwG7o9MkApTmMACo8ErR2x0q2bJ68glvkGYqDjADv/TunVuJfxtJzE1AercJE0IbQikntry6YKwEqwAtV/azv65niTaLSZiUCXH2KkJfZ4lBmKYiaWSzvhAzoepV51w7IoRu89KWMXDIEzhhl9HHl4CcvRwMDpdhyDC5Jz9JMm2lCwiCuFtzXzGB8RaElS0d8HDo4lJtJ3uH2GIBsYSshD2KpzH/fC6BwC5Y36B1KEqqFq/8LWwTgUOUdG8nOx9MI47zHTtAbV6guUBbYsSCMziAw5v08nKb/GKZQ=
  on:
    tags: true
    repo: cogniteev/yamlious
notifications:
  slack:
    secure: Pti6WROwFYs9Ymdya7ngHqYM66s1gFfoo+swIrZGjys1BlYiSvgsGkJop57wQjm3o0mxyjdqF+fVSiuMEh1Qdvt3sKlE7VOcBxSwdl6+FjVevJWTU3eB9od/xe3L63w/OgxuSv2yE/YBqM9huocF+LwGOymwlN1ZhjG5NK0bEO9FaQ0YhHNVMVyIx13C9fPMEHsRk07ewRAbwV6k/uEdh1qsrredGQ/aqfGLf62+fFw5YG+BTqgjtTvST19Kc6RssBxjkVr4I5KZn6r+TgRyYmX2vLdCzAj4mW2bO/CJm2bhYp/b+WqGfabNa2T4YdocOc8Tljy+UI5XTDbgksrJ8pQFl5VOeJb36y92RWdMJEjoUMkpSyE63sjOH///3ewmwYcnWwdVGa3YnQv4yLd8QOT1ieLzMn4o1vAxXvdRkOhFdEjz8u+2hV9T1jCDKm2PGpo+ePCaXShwwpVm96oOzWHigRyUGMPKhMwChSmbqMPMjIqAC+4txrNYAvAJz0+UrhhV64P/tqF8zA/hyjIGx2K+diBKNqgdoonGJBrvKw11WYWh4vyfbPTwotnOgV6KWU9R1zxxckaA8W4XZlDrB1MDatfqFTXPPJYJpy3HcM8/8ydAnOTCbnZzGUXYZl6mec5OftAaKtADvyhL3++JfXP02/q0iaBJQuaifPmEgl4=
