language: python
sudo: required
python:
- '2.7'
install:
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install tox>=2.3.1 coveralls
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . )
after_success: coveralls --verbose
branches:
  only:
  - master
  - /^v.*$/
deploy:
  provider: pypi
  user: tcarel
  password:
    secure: Gi0fEiXWWAmdl9PLKAjinvKVFb1KYKqj1FVxIA/ZOIV4uNpz38HHyLvGI+DSvqoEKmqfPg4uT6DGYv8LeexbP0SMLrT73Qh4wPjaxGTTlnLgypzStnchzzTF+/eZJSxsZPsWO5WD0iakSiyO11jxhdK7RbqLfYS/+XCl78a6/wh7cK2PZ6tIgi985SaClbLsQtzd9EdEsPyoo6V3L8VDutY7F5SzVg13V05kMC7KApM1Iulh+iwVePn/iMHAErrl2i4voFWE+RePgTIFYoIViq8Rew1V14Qe78hiT1AKsoi37F1d5ThLiIB3LWvGN6ZF2qaL9XpQ9aPuOFpuJ6PsL0mOPE+6KjbvWwN25daGIbidoUyEHDrjtZhbD8c1pQWPWkJ01TzwG7o9MkApTmMACo8ErR2x0q2bJ68glvkGYqDjADv/TunVuJfxtJzE1AercJE0IbQikntry6YKwEqwAtV/azv65niTaLSZiUCXH2KkJfZ4lBmKYiaWSzvhAzoepV51w7IoRu89KWMXDIEzhhl9HHl4CcvRwMDpdhyDC5Jz9JMm2lCwiCuFtzXzGB8RaElS0d8HDo4lJtJ3uH2GIBsYSshD2KpzH/fC6BwC5Y36B1KEqqFq/8LWwTgUOUdG8nOx9MI47zHTtAbV6guUBbYsSCMziAw5v08nKb/GKZQ=
  on:
    tags: true
    repo: cogniteev/yamlious
notifications:
  slack:
    secure: icCBQ/pHMj9BZSRdOayqbvDenFAiTTzxEtccXWJR78ob2iybyMKVFgxo0IaIpRAY0CEc70WT1r19X6xtoVyY2PkkSdGG1FJhQ+cMpJkwWA23j6UR/EZsEmJsiIN1fARmXfzKkbaugJIZErbbcbKvIA/NaZE3aFOju2H++7RRY5n/VLtbT1OnSGn88dOfZ2X7EfdbKsu6EtxU5tKloabEqDBK81F8g2RPtnhDIkOdYzfk7kUq+9ud+AcEjNaL7Ya3H9Ghz3YxkuUhaSLRVjSuINV7EOzgJIXnJ0+5NFb8kfz72P7AXGS8PEwlHG195m0R7r5GsbckwdW3RN9j5gcLC1x5Q4DiSncgUdf591NElNnJglVEr/akFx/rf3PPeaWAnZ81rERWtrIsoDm5HkyNmmRsNNOkVGAjUmR41U/Dgfjf2FxcZDVSsAP1OfV8RNJoR7AGYqr+y60zSkT1UGxE1O9sEtmjiCFtwwp40ErNvgMmR8Q7EIh2o7OLDWsxJ86BRwZx0meuzNuDCGNZOFbaGqh735UFE2nWKH/wC2YgEson+xpEr01tem7ZTzcs2fWkCLVhoaH+t0TPKjhLWNu8HU6niIzU5kJ+FKhF2tax7qH4y3AdNr0CQptPlnuRUa65t+izkTZw01F/N+7v2yVWMHebOwXWF4+NKWPT7M++df4=
